### ISSUE TITLE
EffectiveClassMarginLoss is not in the models registry

### ISSUE THREAD

**Issue by guo-yong-zhi** [janghyuncho/ECM-Loss#1]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Traceback (most recent call last):                                                                                                                        
  File "/data/anaconda3/envs/ecm_loss/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg                                     
    return obj_cls(**args)                                                                                                                                
  File "/home/guoyongzhi/ECM-Loss/mmdet/models/roi_heads/base_roi_head.py", line 30, in __init__                                                          
    self.init_bbox_head(bbox_roi_extractor, bbox_head)                                                                                                    
  File "/home/guoyongzhi/ECM-Loss/mmdet/models/roi_heads/standard_roi_head.py", line 26, in init_bbox_head                                                
    self.bbox_head = build_head(bbox_head)                                                                                                                
  File "/home/guoyongzhi/ECM-Loss/mmdet/models/builder.py", line 40, in build_head                                                                        
    return HEADS.build(cfg)                                                                                                                               
  File "/data/anaconda3/envs/ecm_loss/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build                                             
    return self.build_func(*args, **kwargs, registry=self)                                                                                                
  File "/data/anaconda3/envs/ecm_loss/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg                                  
    return build_from_cfg(cfg, registry, default_args)                                                                                                    
  File "/data/anaconda3/envs/ecm_loss/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg                                     
    raise type(e)(f'{obj_cls.__name__}: {e}')                                                                                                             
KeyError: "Shared2FCBBoxHead: 'EffectiveClassMarginLoss is not in the models registry'"     

### Environment

sys.platform: linux                                                                                                                                       
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]                                                                                              
CUDA available: True                                                                                                                                      
GPU 0,1,2,3: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: None
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu116
OpenCV: 4.7.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMDetection: 2.25.2+3e15d48

### Additional information

I followed the steps in `Setup` section of the README to try to reproduce the experiment. But the local `mmdet` in the repo seems not effective.

**Comment by Brym-Gyimah** [comment]
navigate to the ECM-Loss/mmdet/models/losses/__init__.py file 
add this "from .effective_class_margin_loss import EffectiveClassMarginLoss" to the file and also add EffectiveClassMarginLoss to __all__
